# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# TCL: /home/okazaki/projects/mpsoc-on-endcap-sl/Mercury_XU5_PE1_Reference_Design/reference_design/src/Mercury_XU5_rgmii_loc.tcl

# TCL: /home/okazaki/projects/mpsoc-on-endcap-sl/Mercury_XU5_PE1_Reference_Design/reference_design/src/Mercury_XU5_PE1.tcl

# XDC: /home/okazaki/projects/mpsoc-on-endcap-sl/Mercury_XU5_PE1_Reference_Design/reference_design/src/Mercury_XU5_rgmii_timing.xdc

# XDC: /home/okazaki/projects/mpsoc-on-endcap-sl/Mercury_XU5_PE1_Reference_Design/reference_design/src/Mercury_XU5_LED_timing.xdc

# Block Designs: bd/Mercury_XU5/Mercury_XU5.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mercury_XU5 || ORIG_REF_NAME==Mercury_XU5} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_zynq_ultra_ps_e_0/Mercury_XU5_zynq_ultra_ps_e_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mercury_XU5_zynq_ultra_ps_e_0 || ORIG_REF_NAME==Mercury_XU5_zynq_ultra_ps_e_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_system_management_wiz_0/Mercury_XU5_system_management_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mercury_XU5_system_management_wiz_0 || ORIG_REF_NAME==Mercury_XU5_system_management_wiz_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_led_0/Mercury_XU5_led_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mercury_XU5_led_0 || ORIG_REF_NAME==Mercury_XU5_led_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_ddr4_0/Mercury_XU5_ddr4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mercury_XU5_ddr4_0 || ORIG_REF_NAME==Mercury_XU5_ddr4_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_smartconnect_1_0/Mercury_XU5_smartconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mercury_XU5_smartconnect_1_0 || ORIG_REF_NAME==Mercury_XU5_smartconnect_1_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_clk_wiz_0_0/Mercury_XU5_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mercury_XU5_clk_wiz_0_0 || ORIG_REF_NAME==Mercury_XU5_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_smartconnect_0_0/Mercury_XU5_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mercury_XU5_smartconnect_0_0 || ORIG_REF_NAME==Mercury_XU5_smartconnect_0_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_ps_sys_rst_0/Mercury_XU5_ps_sys_rst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mercury_XU5_ps_sys_rst_0 || ORIG_REF_NAME==Mercury_XU5_ps_sys_rst_0} -quiet] -quiet

# IP: bd/Mercury_XU5/ip/Mercury_XU5_ddr4_sys_rst_0/Mercury_XU5_ddr4_sys_rst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mercury_XU5_ddr4_sys_rst_0 || ORIG_REF_NAME==Mercury_XU5_ddr4_sys_rst_0} -quiet] -quiet

# XDC: bd/Mercury_XU5/Mercury_XU5_ooc.xdc
