# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/slave_part.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_chip2chip_0_0/design_1_axi_chip2chip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_chip2chip_0_0 || ORIG_REF_NAME==design_1_axi_chip2chip_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_aurora_64b66b_0_0/design_1_aurora_64b66b_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_aurora_64b66b_0_0 || ORIG_REF_NAME==design_1_aurora_64b66b_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ila_0_0 || ORIG_REF_NAME==design_1_ila_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_2_1/design_1_clk_wiz_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_2_1 || ORIG_REF_NAME==design_1_clk_wiz_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_counter_0_0/design_1_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_counter_0_0 || ORIG_REF_NAME==design_1_counter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ila_1_0/design_1_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ila_1_0 || ORIG_REF_NAME==design_1_ila_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_heartbeat_0_0/design_1_heartbeat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_heartbeat_0_0 || ORIG_REF_NAME==design_1_heartbeat_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
