# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/okazaki/projects/mpsoc-on-endcap-sl/MercuryXU5_EndcapSL/MercuryXU5_EndcapSL.srcs/sources_1/bd/design_1/ip/design_1_debug_bridge_2_0/design_1_debug_bridge_2_0.xci
# IP: The module: 'design_1_debug_bridge_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/okazaki/projects/mpsoc-on-endcap-sl/MercuryXU5_EndcapSL/MercuryXU5_EndcapSL.srcs/sources_1/bd/design_1/ip/design_1_debug_bridge_2_0/bd_0/bd_04e2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04e2 || ORIG_REF_NAME==bd_04e2} -quiet] -quiet

# IP: /home/okazaki/projects/mpsoc-on-endcap-sl/MercuryXU5_EndcapSL/MercuryXU5_EndcapSL.srcs/sources_1/bd/design_1/ip/design_1_debug_bridge_2_0/bd_0/ip/ip_0/bd_04e2_axi_jtag_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04e2_axi_jtag_0 || ORIG_REF_NAME==bd_04e2_axi_jtag_0} -quiet] -quiet

# XDC: /home/okazaki/projects/mpsoc-on-endcap-sl/MercuryXU5_EndcapSL/MercuryXU5_EndcapSL.srcs/sources_1/bd/design_1/ip/design_1_debug_bridge_2_0/bd_0/bd_04e2_ooc.xdc

# XDC: /home/okazaki/projects/mpsoc-on-endcap-sl/MercuryXU5_EndcapSL/MercuryXU5_EndcapSL.srcs/sources_1/bd/design_1/ip/design_1_debug_bridge_2_0/design_1_debug_bridge_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_debug_bridge_2_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/okazaki/projects/mpsoc-on-endcap-sl/MercuryXU5_EndcapSL/MercuryXU5_EndcapSL.srcs/sources_1/bd/design_1/ip/design_1_debug_bridge_2_0/design_1_debug_bridge_2_0.xci
# IP: The module: 'design_1_debug_bridge_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/okazaki/projects/mpsoc-on-endcap-sl/MercuryXU5_EndcapSL/MercuryXU5_EndcapSL.srcs/sources_1/bd/design_1/ip/design_1_debug_bridge_2_0/bd_0/bd_04e2.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04e2 || ORIG_REF_NAME==bd_04e2} -quiet] -quiet

# IP: /home/okazaki/projects/mpsoc-on-endcap-sl/MercuryXU5_EndcapSL/MercuryXU5_EndcapSL.srcs/sources_1/bd/design_1/ip/design_1_debug_bridge_2_0/bd_0/ip/ip_0/bd_04e2_axi_jtag_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04e2_axi_jtag_0 || ORIG_REF_NAME==bd_04e2_axi_jtag_0} -quiet] -quiet

# XDC: /home/okazaki/projects/mpsoc-on-endcap-sl/MercuryXU5_EndcapSL/MercuryXU5_EndcapSL.srcs/sources_1/bd/design_1/ip/design_1_debug_bridge_2_0/bd_0/bd_04e2_ooc.xdc

# XDC: /home/okazaki/projects/mpsoc-on-endcap-sl/MercuryXU5_EndcapSL/MercuryXU5_EndcapSL.srcs/sources_1/bd/design_1/ip/design_1_debug_bridge_2_0/design_1_debug_bridge_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_debug_bridge_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
